# # Generated by the protocol buffer compiler.  DO NOT EDIT!
# # source: nyct-subway.proto
#
# require 'google/protobuf'
#
# require_relative 'gtfs-realtime_pb'
# Google::Protobuf::DescriptorPool.generated_pool.build do
#   add_message "TripReplacementPeriod" do
#     optional :route_id, :string, 1
#     optional :replacement_period, :message, 2, "transit_realtime.TimeRange"
#   end
#   add_message "NyctFeedHeader" do
#     optional :nyct_subway_version, :string, 1
#     repeated :trip_replacement_period, :message, 2, "TripReplacementPeriod"
#   end
#   add_message "NyctTripDescriptor" do
#     optional :train_id, :string, 1
#     optional :is_assigned, :bool, 2
#     optional :direction, :enum, 3, "NyctTripDescriptor.Direction"
#   end
#   add_enum "NyctTripDescriptor.Direction" do
#     value :DUMMY, 0
#     value :NORTH, 1
#     value :EAST, 2
#     value :SOUTH, 3
#     value :WEST, 4
#   end
#   add_message "NyctStopTimeUpdate" do
#     optional :scheduled_track, :string, 1
#     optional :actual_track, :string, 2
#   end
# end
#
# TripReplacementPeriod = Google::Protobuf::DescriptorPool.generated_pool.lookup("TripReplacementPeriod").msgclass
# NyctFeedHeader = Google::Protobuf::DescriptorPool.generated_pool.lookup("NyctFeedHeader").msgclass
# NyctTripDescriptor = Google::Protobuf::DescriptorPool.generated_pool.lookup("NyctTripDescriptor").msgclass
# NyctTripDescriptor::Direction = Google::Protobuf::DescriptorPool.generated_pool.lookup("NyctTripDescriptor.Direction").enummodule
# NyctStopTimeUpdate = Google::Protobuf::DescriptorPool.generated_pool.lookup("NyctStopTimeUpdate").msgclass
