Line.destroy_all

s_1 = Line.create(name: "1")
s_2 = Line.create(name: "2")
s_3 = Line.create(name: "3")
s_4 = Line.create(name: "4")
s_5 = Line.create(name: "5")
s_6 = Line.create(name: "6")
s_7 = Line.create(name: "7")
s_A = Line.create(name: "A")
s_B = Line.create(name: "B")
s_C = Line.create(name: "C")
s_D = Line.create(name: "D")
s_E = Line.create(name: "E")
s_F = Line.create(name: "F")
s_G = Line.create(name: "G")
s_H = Line.create(name: "H")
s_J = Line.create(name: "J")
s_L = Line.create(name: "L")
s_M = Line.create(name: "M")
s_N = Line.create(name: "N")
s_Q = Line.create(name: "Q")
s_R = Line.create(name: "R")
s_S = Line.create(name: "S")
s_V = Line.create(name: "V")
s_W = Line.create(name: "W")
s_Z = Line.create(name: "Z")
s_SIR = Line.create(name: "SI")
